BuzonQuejas3/Models/Queja.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace BuzonQuejas3.Models
{
    public partial class Queja
    {
        public Guid QuejaID { get; set; }

        [Required(ErrorMessage = "Debe llenar este campo")]
        [StringLength(13)]
        public string Folio { get; set; }
        
        [Required(ErrorMessage = "Debe llenar este campo")]
        [StringLength(50)]
        public string NombreQuejante { get; set; }
        
        [Required(ErrorMessage = "Debe llenar este campo")]
        [StringLength(50)]
        public string ApellidoPQuejante { get; set; }
        
        [Required(ErrorMessage = "Debe llenar este campo")]
        [StringLength(50)]
        public string ApellidoMQuejante { get; set; }

        [Required(ErrorMessage = "Debe llenar este campo")]
        [StringLength(100)]
        public string Direccion { get; set; }

        [Required(ErrorMessage = "Debe llenar este campo")]
        [StringLength(20)]
        public string Telefono { get; set; }

        [Required(ErrorMessage = "Debe llenar este campo")]
        [StringLength(40)]
        //[DataType(DataType.EmailAddress,]
        [EmailAddress(ErrorMessage = "Ingresa un correo electrónico con el formato correcto")]

        public string Correo { get; set; }

        [Required(ErrorMessage = "Debe llenar este campo")]
        //[StringLength(400)]
        public string RelatoHechos { get; set; }

        [Required(ErrorMessage = "Debe llenar este campo")]
        [StringLength(50)]
        public string NombreServidor { get; set; }
        
        [Required(ErrorMessage = "Debe llenar este campo")]
        [StringLength(50)]
        public string ApellidoPServidor { get; set; }
        
        [Required(ErrorMessage = "Debe llenar este campo")]
        [StringLength(50)]
        public string ApellidoMServidor { get; set; }

        [Required(ErrorMessage = "Debe llenar este campo")]
        [Display(Name = "Fecha de creación")]
        //[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime FechaCreacion { get; set; }

        [Required(ErrorMessage = "Debe llenar este campo")]
        [StringLength(20)]
        public string Estatus { get; set; }

        public DateTime? FechaAtencion { get; set; }

        [Required(ErrorMessage = "Debe llenar este campo")]
        [StringLength(50)]
        public string NombreAtendio { get; set; }
        
        [Required(ErrorMessage = "Debe llenar este campo")]
        [StringLength(50)]
        public string ApellidoPAtendio { get; set; }
        
        [Required(ErrorMessage = "Debe llenar este campo")]
        [StringLength(50)]
        public string ApellidoMAtendio { get; set; }

        [Required(ErrorMessage = "Debe llenar este campo")]
        [StringLength(300)]
        public string Resolucion { get; set; }
        
        [StringLength(300)]
        public string NumeroPrevio { get; set; }

        //Llave foranea Unidad Remitente
        [Required(ErrorMessage = "Debe llenar este campo")]
        public Guid UnidadRemitenteID { get; set; }

        [ForeignKey("UnidadRemitenteID")]
        public UnidadRemitente UnidadRemitente { get; set; }

        //Llave foranea Municipio
        [Required(ErrorMessage = "Debe llenar este campo")]
        public Guid MunicipioID { get; set; }

        [ForeignKey("MunicipioID")]
        public Municipio Municipio{ get; set; }

        //Llave foranea UnidadAdministrativa
        [Required(ErrorMessage = "Debe llenar este campo")]
        public Guid UnidadAdministrativaID { get; set; }

        [ForeignKey("UnidadAdministrativaID")]
        public UnidadAdministrativa UnidadAdministrativa { get; set; }
        
        //Llave foranea Medio
        [Required(ErrorMessage = "Debe llenar este campo")]
        public Guid MedioID { get; set; }

        [ForeignKey("MedioID")]
        public Medio Medio { get; set; }
        
        //Llave foranea Cargo
        [Required(ErrorMessage = "Debe llenar este campo")]
        public Guid CargoID { get; set; }

        [ForeignKey("CargoID")]
        public Cargo Cargo { get; set; }
        
        //Llave foranea Motivo
        [Required(ErrorMessage = "Debe llenar este campo")]
        public Guid MotivoID { get; set; }

        [ForeignKey("MotivoID")]
        public Motivo Motivo { get; set; }

    }
}

BuzonQuejas3/Controllers/QuejaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BuzonQuejas3.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;


//autenticación
using Microsoft.AspNetCore.Authorization;

namespace BuzonQuejas3.Controllers
{
    public class QuejaController : Controller
    {
        private readonly Dev_BuzonQuejasContext _context;

        public QuejaController(Dev_BuzonQuejasContext context)
        {
            _context = context;
        }

        // GET: Queja
        [Authorize(Roles = "Administrador,Root,UnidadAdministrativa,UnidadRemitente,Fiscal")]
        public async Task<IActionResult> Quejas(string buscar, String filtro)
        {
            IQueryable<QuejaMostrar> quejasMostrar;

            if (User.IsInRole("Administrador") || User.IsInRole("Root") || User.IsInRole("Fiscal"))
            {
                //quejas = from Queja in _context.Quejas select Queja;
                quejasMostrar = from queja in _context.Quejas
                                join medio in _context.Medios on queja.MedioID equals medio.MedioID
                                join motivo in _context.Motivos on queja.MotivoID equals motivo.MotivoID
                                select new QuejaMostrar
                                {
                                    QuejaID = queja.QuejaID,
                                    Folio = queja.Folio,
                                    NombreQuejante = queja.NombreQuejante,
                                    ApellidoPQuejante = queja.ApellidoPQuejante,
                                    ApellidoMQuejante = queja.ApellidoMQuejante,
                                    MotivoQueja = motivo.Descripcion,
                                    NombreServidor = queja.NombreServidor,
                                    ApellidoPServidor = queja.ApellidoPServidor,
                                    ApellidoMServidor = queja.ApellidoMServidor,
                                    FechaCreacion = queja.FechaCreacion,
                                    Estatus = queja.Estatus,
                                    UnidadRemitenteID = queja.UnidadRemitenteID,
                                    MedioID = medio.MedioID,
                                    Medio = medio.Nombre,
                                };
            }
            else if (User.IsInRole("UnidadRemitente"))
            {
                //var unidadRemitenteUsuario = HttpContext.User.FindFirst("UnidadRemitenteID").Value;
                var unidadRemitenteUsuario = User.Claims.ElementAt(2).Value;
                quejasMostrar = from queja in _context.Quejas
                                join medio in _context.Medios on queja.MedioID equals medio.MedioID
                                join motivo in _context.Motivos on queja.MotivoID equals motivo.MotivoID
                                where queja.UnidadRemitenteID == Guid.Parse(unidadRemitenteUsuario)
                                select new QuejaMostrar
                                {
                                    QuejaID = queja.QuejaID,
                                    Folio = queja.Folio,
                                    NombreQuejante = queja.NombreQuejante,
                                    ApellidoPQuejante = queja.ApellidoPQuejante,
                                    ApellidoMQuejante = queja.ApellidoMQuejante,
                                    MotivoQueja = motivo.Descripcion,
                                    NombreServidor = queja.NombreServidor,
                                    ApellidoPServidor = queja.ApellidoPServidor,
                                    ApellidoMServidor = queja.ApellidoMServidor,
                                    FechaCreacion = queja.FechaCreacion,
                                    Estatus = queja.Estatus,
                                    UnidadRemitenteID = queja.UnidadRemitenteID,
                                    MedioID = medio.MedioID,
                                    Medio = medio.Nombre,
                                };
            }
            else if (User.IsInRole("UnidadAdministrativa"))
            {
                var unidadUsuario = User.Claims.ElementAt(3).Value;
                quejasMostrar = from queja in _context.Quejas
                                join medio in _context.Medios on queja.MedioID equals medio.MedioID
                                join motivo in _context.Motivos on queja.MotivoID equals motivo.MotivoID
                                where queja.UnidadAdministrativaID == Guid.Parse(unidadUsuario)
                                select new QuejaMostrar
                                {
                                    QuejaID = queja.QuejaID,
                                    Folio = queja.Folio,
                                    NombreQuejante = queja.NombreQuejante,
                                    ApellidoPQuejante = queja.ApellidoPQuejante,
                                    ApellidoMQuejante = queja.ApellidoMQuejante,
                                    MotivoQueja = motivo.Descripcion,
                                    NombreServidor = queja.NombreServidor,
                                    ApellidoPServidor = queja.ApellidoPServidor,
                                    ApellidoMServidor = queja.ApellidoMServidor,
                                    FechaCreacion = queja.FechaCreacion,
                                    Estatus = queja.Estatus,
                                    UnidadRemitenteID = queja.UnidadRemitenteID,
                                    MedioID = medio.MedioID,
                                    Medio = medio.Nombre,
                                };
            }
            else
            {
                return RedirectToAction("Index", "Acceso");
            }

            if (!String.IsNullOrEmpty(buscar))
            {
                quejasMostrar = quejasMostrar.Where(s => s.NombreQuejante!.Contains(buscar) || s.ApellidoPQuejante!.Contains(buscar) || s.ApellidoMQuejante!.Contains(buscar) || s.NombreServidor!.Contains(buscar) || s.ApellidoPServidor!.Contains(buscar) || s.ApellidoMServidor!.Contains(buscar) || s.Folio!.Contains(buscar));
                ViewData["filtroBuscar"] = buscar;
            }
            else
            {
                ViewData["filtroBuscar"] = "";
            }

            ViewData["FiltroFolio"] = String.IsNullOrEmpty(filtro) ? "FolioDescendiente" : "";
            ViewData["FiltroMedio"] = filtro == "MedioAscendente" ? "MedioDescendiente" : "MedioAscendente";
            ViewData["FiltroFecha"] = filtro == "FechaAscendente" ? "FechaDescendiente" : "FechaAscendente";
            ViewData["FiltroEstatus"] = filtro == "EstatusAscendente" ? "EstatusDescendiente" : "EstatusAscendente";

            switch (filtro)
            {
                case "FolioDescendiente":
                    quejasMostrar = quejasMostrar.OrderByDescending(queja => queja.Folio);
                    break;

                case "EstatusDescendiente":
                    quejasMostrar = quejasMostrar.OrderByDescending(queja => queja.Estatus);
                    break;

                case "MedioDescendiente":
                    quejasMostrar = quejasMostrar.OrderByDescending(queja => queja.MedioID);
                    break;

                case "FechaDescendiente":
                    quejasMostrar = quejasMostrar.OrderByDescending(queja => queja.FechaCreacion);
                    break;

                case "EstatusAscendente":
                    quejasMostrar = quejasMostrar.OrderBy(queja => queja.Estatus);
                    break;

                case "MedioAscendente":
                    quejasMostrar = quejasMostrar.OrderBy(queja => queja.MedioID);
                    break;

                case "FechaAscendente":
                    quejasMostrar = quejasMostrar.OrderBy(queja => queja.FechaCreacion);
                    break;

                default:
                    quejasMostrar = quejasMostrar.OrderBy(queja => queja.Folio);
                    break;
            }

            return View(await quejasMostrar.ToListAsync());
        }

        // GET: Queja/Details/5 No se ocupa
        [Authorize(Roles = "Administrador,Root,Fiscal")]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var queja = await _context.Quejas
                .FirstOrDefaultAsync(m => m.QuejaID == id);
            if (queja == null)
            {
                return NotFound();
            }

            return View(queja);
        }

        [Authorize(Roles = "Administrador,Root,UnidadRemitente,Fiscal")]
        // GET: Queja/Create
        public IActionResult AgregarQueja()
        {
            var lMunicipios = _context.Municipios.ToList();
            var listaMunicipios = new SelectList(lMunicipios.OrderBy(o => o.Nombre), "MunicipioID", "Nombre");
            ViewBag.municipios = listaMunicipios;

            var lCargos = _context.Cargos.ToList();
            var listaCargos = new SelectList(lCargos.OrderBy(o => o.Nombre), "CargoID", "Nombre");
            ViewBag.cargos = listaCargos;

            var lMedios = _context.Medios.ToList();
            var listaMedios = new SelectList(lMedios.OrderBy(o => o.Nombre).Where(m=>m.Nombre != "Buzón web"), "MedioID", "Nombre");
            ViewBag.medios = listaMedios;

            var lMotivos = _context.Motivos.ToList();
            var listaMotivos = new SelectList(lMotivos.OrderBy(o => o.Descripcion), "MotivoID", "Descripcion", "UnidadAdministrativa");
            ViewBag.motivos = listaMotivos;

            return View();
        }

        // POST: Queja/Create
        [HttpPost]
        [ValidateAntiForgeryToken]

BuzonQuejas3/Views/Queja/Create.cshtml
@model BuzonQuejas3.Models.Queja
@*@using Microsoft.AspNetCore.Identity*@

@{
    ViewData["Title"] = "Nueva Queja";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var DepartamentoUsuario = Context.User.FindFirst("DepartamentoID").Value;

}

<link rel="stylesheet" href="~/css/CrearQueja.css" />

<div class="row justify-content-center mt-5">
    <div class="col-12 ">
        <h1 class="text-center titulo-nueva">Nueva Queja</h1>
    </div>
    @{
        if (ViewBag.SuccessMessage != null)
        {
            <div class="col-12">
                <div class="row justify-content-center">
                    <div class="col-6">
                        @*<a asp-action="Create" class="btn seguimiento-bttn ">Nueva</a>*@
                        <div class="modal fade modal-ok" id="exampleModal" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Tarea exitosa</h5>
                                        @*<button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>*@
                                    </div>
                                    <div class="modal-body">
                                        <strong>@ViewBag.SuccessMessage</strong>
                                    </div>
                                    <div class="modal-footer">
                                        @*<button asp-action="Create" type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>*@
                                        <a asp-action="Index" class="btn aceptar-bttn">Aceptar</a>
                                        @*<a asp-action="Create" class="btn aceptar-bttn">Aceptar</a>*@
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </div>

        }
    }
    <div class="col-6">

        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Estatus" value="Pendiente" />
            <input type="hidden" asp-for="AtendidoPor" value="na" />
            <input type="hidden" asp-for="Resolucion" value="na" />
            <input type="hidden" asp-for="Folio" value="na" />
            <input type="hidden" asp-for="FechaAtencion" value="@DateTime.Now" />
            <input type="hidden" asp-for="DepartamentoID" value=@DepartamentoUsuario />
            <input type="hidden" asp-for="UnidadAdministrativaID" value="88f8cf91-458b-438c-b882-75a842387c64" />
            <div class="form-group mt-3">
                <input asp-for="NombreQuejante" class="form-control" placeholder="Nombre*" />
                <span asp-validation-for="NombreQuejante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="Direccion" class="form-control" placeholder="Dirección*" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <select asp-for="MunicipioID" asp-items="ViewBag.municipios" class="form-control">
                    <option value="">Seleccione un municipio</option>
                </select>
                <span asp-validation-for="MunicipioID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <select asp-for="MedioID" asp-items="ViewBag.medios" class="form-control">
                    <option value="">Seleccione un medio de recepción</option>
                </select>
                <span asp-validation-for="MedioID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="Telefono" class="form-control" placeholder="Teléfono*" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="Correo" type="email" class="form-control" placeholder="Correo eléctronico*" />
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="MotivoQueja" class="form-control" placeholder="Motivo de la queja*" />
                <span asp-validation-for="MotivoQueja" class="text-danger"></span>
            </div>
            <div class="form-group">
                <textarea asp-for="RelatoHechos" class="form-control" placeholder="Relato de hechos*">
                </textarea>
                <span asp-validation-for="RelatoHechos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="ServidorInvolucrado" class="form-control" placeholder="Servidor público involucrado*" />
                <span asp-validation-for="ServidorInvolucrado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <select asp-for="CargoID" asp-items="ViewBag.cargos" class="form-control cargoSelect">
                    <option value="">Seleccione un cargo</option>
                </select>
                <span asp-validation-for="CargoID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Fecha de creación*</label>
                <input asp-for="FechaCreacion" class="form-control" />
                <span asp-validation-for="FechaCreacion" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Enviar" class="btn enviar-bttn-queja" />
            </div>
        </form>

    </div>
</div>



@section Scripts {
<script src="~/js/CrearQueja.js" asp-append-version="true"></script>
}

BuzonQuejas3/Views/Queja/Index.cshtml
@*@model IEnumerable<BuzonQuejas3.Models.Queja>*@
@model IEnumerable<BuzonQuejas3.Models.QuejaMostrar>
@using Microsoft.AspNetCore.Identity
@{
    ViewData["Title"] = "Inicio";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var nombreUsuario = User.Claims.ElementAt(0).Value;
}
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" href="~/css/IndexQueja.css" />
<div class="row justify-content-center mt-3">
    <div class="col-12">
        <div class="row align-items-center mb-2">
            <div class="col-12">
                <p class="text-center user-name ">@nombreUsuario</p>
            </div>
            <div class="col-12 mb-5">
                <h1 class="text-center titulo">Buzón de quejas  </h1>
            </div>
        </div>
    </div>
    <div class="col-10 align-self-end ">
        <div class="table-responsive border contenedor-tabla">
            <table class="table table-hover ">
                <thead>
                    <tr class="align-text-top header-table">
                        <th class="align-text-top">
                            <a class="text-dark" asp-action="Index" asp-route-filtro="@ViewData["FiltroFolio"]">
                                @Html.DisplayName("Folio")
                                <span class="material-icons size-order ">height</span>
                            </a>
                        </th>
                        <th class="align-text-top">
                            @Html.DisplayName("Nombre del Quejoso")
                        </th>
                        <th class="align-text-top">
                            <a class="text-dark" asp-action="Index" asp-route-filtro="@ViewData["FiltroFecha"]">
                                @Html.DisplayName("Fecha")
                                <span class="material-icons size-order ">height</span>
                            </a>
                        </th>
                        @*@if (User.IsInRole("Administrador") || User.IsInRole("Root"))*@
                        @* { *@
                        <!--<th class="align-text-top col-4 ">
                        <a class="text-dark" asp-action="Index" asp-route-filtro="@ViewData["FiltroUnidad"]">-->
                        @*@Html.DisplayName("Unidad Administrativa")*@
                        <!--Unidad Administrativa
                                <span class="material-icons size-order ">arrow_downward</span>
                            </a>
                        </th>-->
                        @*}
                            else
                            {*@
                        @*<th class="align-text-top col-4 ">
                                @Html.DisplayName("Unidad Administrativa")
                            </th>*@
                        @* }*@
                        <th class="align-text-top">
                            @Html.DisplayName("Motivo")
                        </th>
                        <th class="align-text-top">
                            @Html.DisplayName("Servidor Público Involucrado")
                        </th>
                        <th class="align-text-top">
                            <a class="text-dark" asp-action="Index" asp-route-filtro="@ViewData["FiltroMedio"]">
                                @Html.DisplayName("Medio de Recepción")
                                <span class="material-icons size-order ">height</span>
                            </a>
                        </th>
                        <th class="align-text-top">
                            <a class="text-dark" asp-action="Index" asp-route-filtro="@ViewData["FiltroEstatus"]">
                                <div class="row">
                                    <div class="col-2 mr-4">
                                        @Html.DisplayName("Estatus")
                                    </div>
                                    <div class="col-1 ">
                                        <span class="material-icons size-order ">height</span>
                                    </div>

                                </div>
                            </a>
                        </th>
                        @if (User.IsInRole("Administrador") || User.IsInRole("Root") || User.IsInRole("Departamental"))
                        {
                            <th class="align-text-top">
                                @Html.DisplayName("Reasignar")
                            </th>
                        }
                        @if (User.IsInRole("Administrador") || User.IsInRole("Root") || User.IsInRole("UnidadAdministrativa"))
                        {
                            <th class="align-text-top">
                                @Html.DisplayName("Seguimiento ")
                            </th>
                        }
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr class="table-row">
                            <td>
                                @Html.DisplayFor(modelItem => item.Folio)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.NombreQuejante)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FechaCreacion)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.MotivoQueja)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ServidorInvolucrado)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Medio)
                            </td>
                            <td>
                                @{
                                    if (@item.Estatus == "Pendiente")
                                    {
                                        <p class="text-danger">Pendiente</p>
                                    }
                                    else
                                    {
                                        <p class="text-success">Atendido</p>
                                    }
                                }
                            </td>
                            @if (User.IsInRole("Administrador") || User.IsInRole("Root") || User.IsInRole("Departamental"))
                            {
                                <td class="text-center">
                                    <button type="button" class="btn reasignar reasignar-bttn align-top" data-toggle="modal" data-target="#exampleModal" id="@item.QuejaID">
                                        Reasignar
                                    </button>
                                </td>
                            }

                            @if (User.IsInRole("Administrador") || User.IsInRole("Root") || User.IsInRole("UnidadAdministrativa"))
                            {
                                <td class="text-center">
                                    <a asp-action="Seguimiento" asp-route-id="@item.QuejaID" class="btn seguimiento-bttn "><span class="material-icons size-icon ">shortcut</span></a>
                                </td>
                            }
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="modal fade" id="exampleModal" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header text-center align-content-center">
                        <h5 class="modal-title  " id="exampleModalLabel">Reasignar queja</h5>
                        @*<button type="button" class="close" data-dismiss="modal" aria-label="Close" id="close-modal-bttn">
                                <span aria-hidden="true">&times;</span>
                            </button>*@
                    </div>
                    <div class="modal-body" id="modalReasignar">
                        <form asp-controller="Queja" asp-action="Reasignar">
                            @*<div class="form-group" id="SelectUnidad">
                                    <label for="exampleInputEmail1">Unidad administrativa actual</label>
                                    <textarea readonly class="form-control" id="showID"> </textarea>
                                </div>*@
                            <div class="form-group">
                                <label>Unidad administrativa a reasignar</label>
                                <select class="form-control" id="unidad" name="unidadId">
                                    @*<option id="optionPrincipal"></option>*@
                                </select>
                            </div>
                            <div class="form-group">
                                <input type="text" hidden class="form-control" name="QuejaId" id="QuejaId">
                            </div>
                            <button type="submit" class="btn reasignar-modal-bttn" id="reasignar-bttn">Reasignar</button>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn salir-modal-bttn" data-dismiss="modal" id="salir-bttn">Salir</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
<script src="~/js/Quejas.js" asp-append-version="true"></script>
}