BuzonQuejas3/Controllers/AccesoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using BuzonQuejas3.Models;

using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;
using BuzonQuejas3.Helper;

namespace BuzonQuejas3.Controllers
{
    public class AccesoController : Controller
    {
        private readonly Dev_BuzonQuejasContext _context;

        public AccesoController(Dev_BuzonQuejasContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(Usuario _usuario)
        {
            if (_usuario.Correo != null && _usuario.Clave != null)
            {
                var hash = HashHelper.Hash(_usuario.Clave);

                var usuario = await _context.Usuarios.FirstOrDefaultAsync(m => m.Correo == _usuario.Correo && m.Clave == hash.Password);

                if (usuario != null)
                {
                    if (true.Equals(usuario.Activo))
                    {
                        var rol = await _context.Roles.FirstOrDefaultAsync(m => m.RolID == usuario.RolID);

                        //2.- CONFIGURACION DE LA AUTENTICACION
                        #region AUTENTICACTION
                        var claims = new List<Claim>{
                            new Claim(ClaimTypes.Name, usuario.Nombre),
                            new Claim("Correo", usuario.Correo),
                            new Claim("UnidadRemitenteID", usuario.UnidadRemitenteID.ToString()),
                            new Claim("UnidadAdministrativaID", usuario.UnidadAdministrativaID.ToString()),
                            new Claim(ClaimTypes.Role, rol.Nombre),
                        };
                        var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                        await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));
                        #endregion

                        if (usuario.Clave == "gdnrIvSE0unNNIore1PcbsfdwEP9S7cftX+9UCBTo5s=")
                        {
                            return RedirectToAction("ReestablecerClave", "Usuario", new { id = usuario.UsuarioID });
                        }
                        else
                        {
                            return RedirectToAction("Quejas", "Queja");
                        }
                    }
                    else
                    {
                        ViewBag.SuccessMessage = "Este usuario no está activo";
                        return View();
                    }
                }
                else
                {

                    ViewBag.SuccessMessage = "El usuario y/o la contraseña son incorrectos";
                    return View();
                }
            }
            else
            {
                return View();
            }


        }

        public async Task<IActionResult> Salir()
        {
            //3.- CONFIGURACION DE LA AUTENTICACION
            #region AUTENTICACTION
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            #endregion

            return RedirectToAction("Index");

        }
    }
}

BuzonQuejas3/Views/Acceso/Index.cshtml
@model Usuario
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Iniciar Sesión</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/login.css" />
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <link rel="icon" type="image/png" sizes="32x32" href="~/imagenes/faviconV2.png">
</head>
<body>
    <div class="container h-100">
        <div class="d-flex justify-content-center h-100">
            <div class="user_card">
                <div class="d-flex justify-content-center">
                    <div class="brand_logo_container">
                        <img src="~/imagenes/Logotipo_institucional_SL.png" class="brand_logo" alt="Logo">
                    </div>
                </div>
                <div class="d-flex justify-content-center form_container">
                    <form asp-controller="Acceso" asp-action="Index" method="post">
                        <div class="form-group">
                            <input type="email" asp-for="Correo" class="form-control input_user" placeholder="Correo Electrónico" />
                            <span asp-validation-for="Correo" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="password" asp-for="Clave" class="form-control input_user" placeholder="Contraseña" />
                            <span asp-validation-for="Clave" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            @{
                                if (ViewBag.SuccessMessage != null)
                                {
                                    <div class="alert alert-warning alert-dismissible fade show" style="font-size:12px" role="alert">
                                        <strong>@ViewBag.SuccessMessage</strong>
                                        <button type="button" class="close" data-dismiss="alert">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                }
                            }
                        </div>
                        <div class="d-flex justify-content-center mt-4 login_container">
                            <button type="submit" class="btn login_btn">Ingresar</button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>